# Generated by Django 3.0.7 on 2020-07-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
